In [35]:
import numpy as np
def gram_schmidt(A):
    Q=np.zeros_like(A)
    cnt = 0
    for a in A.T:
        u = np.copy(a)
        for i in range(0, cnt):
            u -= np.dot(np.dot(Q[:, i].T, a), Q[:, i])               
        e = u / np.linalg.norm(u)
        Q[:, cnt] = e
        cnt += 1
    R = np.dot(Q.T, A)
    return (Q, R)

np.set_printoptions(precision=4, suppress=True)
A = np.array([[6, 5, 0],[5, -1, 4],[5, 1, -14],[0, 4, 3]],dtype=float)

(Q, R) = gram_schmidt(A)
print(Q)
print(R)
print (np.dot(Q,R))

[[ 0.647   0.5096  0.1799]
 [ 0.5392 -0.4811  0.5743]
 [ 0.5392 -0.1305 -0.7902]
 [ 0.      0.7013  0.1162]]
[[ 9.2736  3.235  -5.3916]
 [ 0.      5.7039  2.006 ]
 [-0.      0.     13.7079]]
[[  6.   5.   0.]
 [  5.  -1.   4.]
 [  5.   1. -14.]
 [  0.   4.   3.]]


In [31]:
import numpy as np

def gram_schmidt(A):
    Q=np.zeros_like(A)
    cnt = 0
    for a in A.T:
        u = np.copy(a)
        for i in range(0, cnt):
            u -= np.dot(np.dot(Q[:, i].T, a), Q[:, i]) #                  
        e = u / np.linalg.norm(u)  # 
        Q[:, cnt] = e
        cnt += 1
    R = np.dot(Q.T, A)
    return (Q, R)


np.set_printoptions(precision=4, suppress=True)
A = np.array([[6, 5, 0],[5, -1, 4],[5, 1, -14],[0, 4, 3]],dtype=float)

(Q, R) = gram_schmidt(A)
print(Q)
print(R)
print (np.dot(Q,R))



[[ 0.647   0.5096  0.1799]
 [ 0.5392 -0.4811  0.5743]
 [ 0.5392 -0.1305 -0.7902]
 [ 0.      0.7013  0.1162]]
[[ 9.2736  3.235  -5.3916]
 [ 0.      5.7039  2.006 ]
 [-0.      0.     13.7079]]
[[  6.   5.   0.]
 [  5.  -1.   4.]
 [  5.   1. -14.]
 [  0.   4.   3.]]


In [33]:
 Q, R = np.linalg.qr(A)
Q
np.dot(Q, R)

array([[  6.,   5.,   0.],
       [  5.,  -1.,   4.],
       [  5.,   1., -14.],
       [  0.,   4.,   3.]])